Traceback (most recent call last):
  File "C:\Users\skorczewskit\Anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\skorczewskit\Anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\skorczewskit\Anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\skorczewskit\Anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\skorczewskit\Anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\skorczewskit\Anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\skorczewskit\Anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\skorczewskit\Anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
A = np.array([[4,0,-1,0],
             [10,0,0,-2],
             [0,2,-2,-1]])

b = np.array([[0,0,0]]).transpose()

x = np.linalg.solve(A,b)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mLinAlgError[0m                               Traceback (most recent call last)
Input [1;32mIn [4][0m, in [0;36m<cell line: 7>[1;34m()[0m
[0;32m      1[0m A [38;5;241m=[39m np[38;5;241m.[39marray([[[38;5;241m4[39m,[38;5;241m0[39m,[38;5;241m-[39m[38;5;241m1[39m,[38;5;241m0[39m],
[0;32m      2[0m              [[38;5;241m10[39m,[38;5;241m0[39m,[38;5;241m0[39m,[38;5;241m-[39m[38;5;241m2[39m],
[0;32m      3[0m              [[38;5;241m0[39m,[38;5;241m2[39m,[38;5;241m-[39m[38;5;241m2[39m,[38;5;241m-[39m[38;5;241m1[39m]])
[0;32m      5[0m b [38;5;241m=[39m np[38;5;241m.[39marray([[[38;5;241m0[39m,[38;5;241m0[39m,[38;5;241m0[39m]])[38;5;241m.[39mtranspose()
[1;32m----> 7[0m x [38;5;241m=[39m [43mnp[49m[38;5;241;43m.[39;49m[43mlinalg[49m[38;5;241;43m.[39;49m[43msolve[49m[43m([49m[43mA[49m[43m,[49m[43mb[49m[43m)[49m

File [1;32m<__array_function__ internals>:5[0m, in [0;36msolve[1;34m(*args, **kwargs)[0m

File [1;32m~\Anaconda3\lib\site-packages\numpy\linalg\linalg.py:380[0m, in [0;36msolve[1;34m(a, b)[0m
[0;32m    378[0m a, _ [38;5;241m=[39m _makearray(a)
[0;32m    379[0m _assert_stacked_2d(a)
[1;32m--> 380[0m [43m_assert_stacked_square[49m[43m([49m[43ma[49m[43m)[49m
[0;32m    381[0m b, wrap [38;5;241m=[39m _makearray(b)
[0;32m    382[0m t, result_t [38;5;241m=[39m _commonType(a, b)

File [1;32m~\Anaconda3\lib\site-packages\numpy\linalg\linalg.py:203[0m, in [0;36m_assert_stacked_square[1;34m(*arrays)[0m
[0;32m    201[0m m, n [38;5;241m=[39m a[38;5;241m.[39mshape[[38;5;241m-[39m[38;5;241m2[39m:]
[0;32m    202[0m [38;5;28;01mif[39;00m m [38;5;241m!=[39m n:
[1;32m--> 203[0m     [38;5;28;01mraise[39;00m LinAlgError([38;5;124m'[39m[38;5;124mLast 2 dimensions of the array must be square[39m[38;5;124m'[39m)

[1;31mLinAlgError[0m: Last 2 dimensions of the array must be square
LinAlgError: Last 2 dimensions of the array must be square

